# Generated by Django 5.2.7 on 2026-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(default='def_image.png', upload_to='thread_images'),
        ),
    ]
